name: milk_mix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_svg: ^2.2.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/milkmix.svg
    - assets/backgrounds/Frame.svg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
    - family: InterDisplay
      fonts:
        - asset: assets/fonts/InterDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/InterDisplay-ExtraBold.ttf
          weight: 800